# vim: sw=2:sts=2
---

node_exporter_listen_addr: ''
node_exporter_listen_port: 9100
node_exporter_disk_ignored_devs:
node_exporter_fs_ignored_mounts: '^/(sys|proc|dev|run)($|/)'
node_exporter_net_ignored_devs: '^lo$'
node_exporter_enabled_collectors:
node_exporter_extra_args:
node_exporter_install_ferm_svc: false
node_exporter_allow_from:
