---
- name: restart prometheus
  service: name=prometheus state=restarted

- name: reload prometheus
  service: name=prometheus state=reloaded

- name: reload ferm
  service: name=ferm state=reloaded
