- name: 'set-up user homes: directories'
  file:
    path: '/home/{{ user.name }}/{{ item.path }}'
    mode: '{{ item.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    state: directory
  with_filetree: '{{ home_dir_templates }}/{{ user.name }}'
  when: item.state == 'directory'

- name: 'set-up user homes: normal files'
  copy:
    src: '{{ item.src }}'
    dest: '/home/{{ user.name }}/{{ item.path | regex_replace("\.j2$", "") }}'
    mode: '{{ item.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
  with_filetree: '{{ home_dir_templates }}/{{ user.name }}'
  when: item.state == 'file' and not item.src.endswith('.j2')

- name: 'set-up user homes: templates'
  template:
    src: '{{ item.src }}'
    dest: '/home/{{ user.name }}/{{ item.path | regex_replace("\.j2$", "") }}'
    mode: '{{ item.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
  with_filetree: '{{ home_dir_templates }}/{{ user.name }}'
  when: item.state == 'file' and item.src.endswith('.j2')

- name: 'set-up user homes: symlinks'
  file:
    src: '{{ item.src }}'
    path: '/home/{{ user.name }}/{{ item.path }}'
    mode: '{{ item.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    state: link
    force: true
    follow: false
  with_filetree: '{{ home_dir_templates }}/{{ user.name }}'
  when: item.state == 'link'
